server:
  address: ":8001"                                         # На каком порту будет работать микросервис seeds
  path_to_log: "./logs"                                    # Путь к логу /var/log/

auth:
  default_password: "123456"                               # Пароль по умолчанию

database:
  host: "localhost"                                        # Хост базы данных
  port: 5432                                               # Порт базы данных
  name: "dev"                                              # Название базы данных
  user: "dev"                                              # Пользователь базы данных
  password: "test"                                         # Пароль базы данных

jwt:
  client_secret: "dev"                                     # Секретный ключ
  expires_in: 1800000                                      # Срок действия токена

serial:
  port: "/dev/cu.usbmodem3377395B33351"                    # Порт устройства
  baud: 115200                                             # Скорость передачи данных

camera:
  name: "HD Pro Webcam C920"                               # Название камеры
  input_device: "avfoundation"                             # Входное устройство
  framerate: "30"                                          # Кадровая частота
  video_size: "1920x1080"                                  # Размер видео

api:
  url: "http://localhost:8001"                             # URL AI API

sqlite:
  path_to_db: "./db/calibration.db"                        # Путь к базе данных
