// Code generated by MockGen. DO NOT EDIT.
// Source: logs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockILogsApp is a mock of ILogsApp interface.
type MockILogsApp struct {
	ctrl     *gomock.Controller
	recorder *MockILogsAppMockRecorder
}

// MockILogsAppMockRecorder is the mock recorder for MockILogsApp.
type MockILogsAppMockRecorder struct {
	mock *MockILogsApp
}

// NewMockILogsApp creates a new mock instance.
func NewMockILogsApp(ctrl *gomock.Controller) *MockILogsApp {
	mock := &MockILogsApp{ctrl: ctrl}
	mock.recorder = &MockILogsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogsApp) EXPECT() *MockILogsAppMockRecorder {
	return m.recorder
}

// GetLogs mocks base method.
func (m *MockILogsApp) GetLogs(arg0 models.LogsParams) ([]models.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", arg0)
	ret0, _ := ret[0].([]models.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockILogsAppMockRecorder) GetLogs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockILogsApp)(nil).GetLogs), arg0)
}
