// Code generated by MockGen. DO NOT EDIT.
// Source: shifts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIShiftsApp is a mock of IShiftsApp interface.
type MockIShiftsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIShiftsAppMockRecorder
}

// MockIShiftsAppMockRecorder is the mock recorder for MockIShiftsApp.
type MockIShiftsAppMockRecorder struct {
	mock *MockIShiftsApp
}

// NewMockIShiftsApp creates a new mock instance.
func NewMockIShiftsApp(ctrl *gomock.Controller) *MockIShiftsApp {
	mock := &MockIShiftsApp{ctrl: ctrl}
	mock.recorder = &MockIShiftsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShiftsApp) EXPECT() *MockIShiftsAppMockRecorder {
	return m.recorder
}

// AddShift mocks base method.
func (m *MockIShiftsApp) AddShift(arg0 models.Shifts) (models.Shifts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShift", arg0)
	ret0, _ := ret[0].(models.Shifts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShift indicates an expected call of AddShift.
func (mr *MockIShiftsAppMockRecorder) AddShift(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShift", reflect.TypeOf((*MockIShiftsApp)(nil).AddShift), arg0)
}

// DeleteShifts mocks base method.
func (m *MockIShiftsApp) DeleteShifts(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShifts", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteShifts indicates an expected call of DeleteShifts.
func (mr *MockIShiftsAppMockRecorder) DeleteShifts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShifts", reflect.TypeOf((*MockIShiftsApp)(nil).DeleteShifts), arg0)
}

// GetShifts mocks base method.
func (m *MockIShiftsApp) GetShifts() ([]models.Shifts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShifts")
	ret0, _ := ret[0].([]models.Shifts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShifts indicates an expected call of GetShifts.
func (mr *MockIShiftsAppMockRecorder) GetShifts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShifts", reflect.TypeOf((*MockIShiftsApp)(nil).GetShifts))
}

// GetShiftsByShift mocks base method.
func (m *MockIShiftsApp) GetShiftsByShift(arg0 string) (models.Shifts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftsByShift", arg0)
	ret0, _ := ret[0].(models.Shifts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftsByShift indicates an expected call of GetShiftsByShift.
func (mr *MockIShiftsAppMockRecorder) GetShiftsByShift(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftsByShift", reflect.TypeOf((*MockIShiftsApp)(nil).GetShiftsByShift), arg0)
}

// GetShiftsWithoutUser mocks base method.
func (m *MockIShiftsApp) GetShiftsWithoutUser() ([]models.Shifts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftsWithoutUser")
	ret0, _ := ret[0].([]models.Shifts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftsWithoutUser indicates an expected call of GetShiftsWithoutUser.
func (mr *MockIShiftsAppMockRecorder) GetShiftsWithoutUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftsWithoutUser", reflect.TypeOf((*MockIShiftsApp)(nil).GetShiftsWithoutUser))
}

// UpdateShifts mocks base method.
func (m *MockIShiftsApp) UpdateShifts(arg0 models.Shifts) (models.Shifts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShifts", arg0)
	ret0, _ := ret[0].(models.Shifts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShifts indicates an expected call of UpdateShifts.
func (mr *MockIShiftsAppMockRecorder) UpdateShifts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShifts", reflect.TypeOf((*MockIShiftsApp)(nil).UpdateShifts), arg0)
}
