// Code generated by MockGen. DO NOT EDIT.
// Source: reports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIReportsApp is a mock of IReportsApp interface.
type MockIReportsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIReportsAppMockRecorder
}

// MockIReportsAppMockRecorder is the mock recorder for MockIReportsApp.
type MockIReportsAppMockRecorder struct {
	mock *MockIReportsApp
}

// NewMockIReportsApp creates a new mock instance.
func NewMockIReportsApp(ctrl *gomock.Controller) *MockIReportsApp {
	mock := &MockIReportsApp{ctrl: ctrl}
	mock.recorder = &MockIReportsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReportsApp) EXPECT() *MockIReportsAppMockRecorder {
	return m.recorder
}

// AddReport mocks base method.
func (m *MockIReportsApp) AddReport(arg0 models.Reports) (models.Reports, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReport", arg0)
	ret0, _ := ret[0].(models.Reports)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddReport indicates an expected call of AddReport.
func (mr *MockIReportsAppMockRecorder) AddReport(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReport", reflect.TypeOf((*MockIReportsApp)(nil).AddReport), arg0)
}

// GetReports mocks base method.
func (m *MockIReportsApp) GetReports() ([]models.Reports, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReports")
	ret0, _ := ret[0].([]models.Reports)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReports indicates an expected call of GetReports.
func (mr *MockIReportsAppMockRecorder) GetReports() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReports", reflect.TypeOf((*MockIReportsApp)(nil).GetReports))
}

// GetReportsByReport mocks base method.
func (m *MockIReportsApp) GetReportsByReport(arg0 string) (models.Reports, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportsByReport", arg0)
	ret0, _ := ret[0].(models.Reports)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportsByReport indicates an expected call of GetReportsByReport.
func (mr *MockIReportsAppMockRecorder) GetReportsByReport(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportsByReport", reflect.TypeOf((*MockIReportsApp)(nil).GetReportsByReport), arg0)
}

// UpdateReport mocks base method.
func (m *MockIReportsApp) UpdateReport(arg0 models.Reports) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReport", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReport indicates an expected call of UpdateReport.
func (mr *MockIReportsAppMockRecorder) UpdateReport(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReport", reflect.TypeOf((*MockIReportsApp)(nil).UpdateReport), arg0)
}
