// Code generated by MockGen. DO NOT EDIT.
// Source: assignments.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIAssignmentsApp is a mock of IAssignmentsApp interface.
type MockIAssignmentsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIAssignmentsAppMockRecorder
}

// MockIAssignmentsAppMockRecorder is the mock recorder for MockIAssignmentsApp.
type MockIAssignmentsAppMockRecorder struct {
	mock *MockIAssignmentsApp
}

// NewMockIAssignmentsApp creates a new mock instance.
func NewMockIAssignmentsApp(ctrl *gomock.Controller) *MockIAssignmentsApp {
	mock := &MockIAssignmentsApp{ctrl: ctrl}
	mock.recorder = &MockIAssignmentsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssignmentsApp) EXPECT() *MockIAssignmentsAppMockRecorder {
	return m.recorder
}

// AddAssignment mocks base method.
func (m *MockIAssignmentsApp) AddAssignment(arg0 models.Assignments) (models.Assignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAssignment", arg0)
	ret0, _ := ret[0].(models.Assignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAssignment indicates an expected call of AddAssignment.
func (mr *MockIAssignmentsAppMockRecorder) AddAssignment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAssignment", reflect.TypeOf((*MockIAssignmentsApp)(nil).AddAssignment), arg0)
}

// CheckActiveTasks mocks base method.
func (m *MockIAssignmentsApp) CheckActiveTasks(arg0 string) ([]models.ActiveTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActiveTasks", arg0)
	ret0, _ := ret[0].([]models.ActiveTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckActiveTasks indicates an expected call of CheckActiveTasks.
func (mr *MockIAssignmentsAppMockRecorder) CheckActiveTasks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActiveTasks", reflect.TypeOf((*MockIAssignmentsApp)(nil).CheckActiveTasks), arg0)
}

// DeleteAssignments mocks base method.
func (m *MockIAssignmentsApp) DeleteAssignments(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssignments", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAssignments indicates an expected call of DeleteAssignments.
func (mr *MockIAssignmentsAppMockRecorder) DeleteAssignments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssignments", reflect.TypeOf((*MockIAssignmentsApp)(nil).DeleteAssignments), arg0)
}

// GetAssignments mocks base method.
func (m *MockIAssignmentsApp) GetAssignments() ([]models.Assignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignments")
	ret0, _ := ret[0].([]models.Assignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignments indicates an expected call of GetAssignments.
func (mr *MockIAssignmentsAppMockRecorder) GetAssignments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignments", reflect.TypeOf((*MockIAssignmentsApp)(nil).GetAssignments))
}

// GetAssignmentsByAssignment mocks base method.
func (m *MockIAssignmentsApp) GetAssignmentsByAssignment(arg0 string) (models.Assignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignmentsByAssignment", arg0)
	ret0, _ := ret[0].(models.Assignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignmentsByAssignment indicates an expected call of GetAssignmentsByAssignment.
func (mr *MockIAssignmentsAppMockRecorder) GetAssignmentsByAssignment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignmentsByAssignment", reflect.TypeOf((*MockIAssignmentsApp)(nil).GetAssignmentsByAssignment), arg0)
}

// GetTaskById mocks base method.
func (m *MockIAssignmentsApp) GetTaskById(arg0 string) (models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskById", arg0)
	ret0, _ := ret[0].(models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskById indicates an expected call of GetTaskById.
func (mr *MockIAssignmentsAppMockRecorder) GetTaskById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskById", reflect.TypeOf((*MockIAssignmentsApp)(nil).GetTaskById), arg0)
}

// UpdateAssignment mocks base method.
func (m *MockIAssignmentsApp) UpdateAssignment(arg0 models.Assignments) (models.Assignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssignment", arg0)
	ret0, _ := ret[0].(models.Assignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAssignment indicates an expected call of UpdateAssignment.
func (mr *MockIAssignmentsAppMockRecorder) UpdateAssignment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssignment", reflect.TypeOf((*MockIAssignmentsApp)(nil).UpdateAssignment), arg0)
}
