// Code generated by MockGen. DO NOT EDIT.
// Source: bunker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIBunkersApp is a mock of IBunkersApp interface.
type MockIBunkersApp struct {
	ctrl     *gomock.Controller
	recorder *MockIBunkersAppMockRecorder
}

// MockIBunkersAppMockRecorder is the mock recorder for MockIBunkersApp.
type MockIBunkersAppMockRecorder struct {
	mock *MockIBunkersApp
}

// NewMockIBunkersApp creates a new mock instance.
func NewMockIBunkersApp(ctrl *gomock.Controller) *MockIBunkersApp {
	mock := &MockIBunkersApp{ctrl: ctrl}
	mock.recorder = &MockIBunkersAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBunkersApp) EXPECT() *MockIBunkersAppMockRecorder {
	return m.recorder
}

// AddBunker mocks base method.
func (m *MockIBunkersApp) AddBunker(arg0 models.Bunkers) (models.Bunkers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBunker", arg0)
	ret0, _ := ret[0].(models.Bunkers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBunker indicates an expected call of AddBunker.
func (mr *MockIBunkersAppMockRecorder) AddBunker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBunker", reflect.TypeOf((*MockIBunkersApp)(nil).AddBunker), arg0)
}

// DeleteBunker mocks base method.
func (m *MockIBunkersApp) DeleteBunker(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBunker", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBunker indicates an expected call of DeleteBunker.
func (mr *MockIBunkersAppMockRecorder) DeleteBunker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBunker", reflect.TypeOf((*MockIBunkersApp)(nil).DeleteBunker), arg0)
}

// GetBunkers mocks base method.
func (m *MockIBunkersApp) GetBunkers() ([]models.Bunkers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBunkers")
	ret0, _ := ret[0].([]models.Bunkers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBunkers indicates an expected call of GetBunkers.
func (mr *MockIBunkersAppMockRecorder) GetBunkers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBunkers", reflect.TypeOf((*MockIBunkersApp)(nil).GetBunkers))
}

// GetBunkersById mocks base method.
func (m *MockIBunkersApp) GetBunkersById(arg0 string) (models.Bunkers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBunkersById", arg0)
	ret0, _ := ret[0].(models.Bunkers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBunkersById indicates an expected call of GetBunkersById.
func (mr *MockIBunkersAppMockRecorder) GetBunkersById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBunkersById", reflect.TypeOf((*MockIBunkersApp)(nil).GetBunkersById), arg0)
}

// GetBunkersForPlacement mocks base method.
func (m *MockIBunkersApp) GetBunkersForPlacement() ([]models.Bunkers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBunkersForPlacement")
	ret0, _ := ret[0].([]models.Bunkers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBunkersForPlacement indicates an expected call of GetBunkersForPlacement.
func (mr *MockIBunkersAppMockRecorder) GetBunkersForPlacement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBunkersForPlacement", reflect.TypeOf((*MockIBunkersApp)(nil).GetBunkersForPlacement))
}

// UpdateBunker mocks base method.
func (m *MockIBunkersApp) UpdateBunker(arg0 models.Bunkers) (models.Bunkers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBunker", arg0)
	ret0, _ := ret[0].(models.Bunkers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBunker indicates an expected call of UpdateBunker.
func (mr *MockIBunkersAppMockRecorder) UpdateBunker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBunker", reflect.TypeOf((*MockIBunkersApp)(nil).UpdateBunker), arg0)
}
