// Code generated by MockGen. DO NOT EDIT.
// Source: calibration.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockICalibrationApp is a mock of ICalibrationApp interface.
type MockICalibrationApp struct {
	ctrl     *gomock.Controller
	recorder *MockICalibrationAppMockRecorder
}

// MockICalibrationAppMockRecorder is the mock recorder for MockICalibrationApp.
type MockICalibrationAppMockRecorder struct {
	mock *MockICalibrationApp
}

// NewMockICalibrationApp creates a new mock instance.
func NewMockICalibrationApp(ctrl *gomock.Controller) *MockICalibrationApp {
	mock := &MockICalibrationApp{ctrl: ctrl}
	mock.recorder = &MockICalibrationAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICalibrationApp) EXPECT() *MockICalibrationAppMockRecorder {
	return m.recorder
}

// BytesFromPhoto mocks base method.
func (m *MockICalibrationApp) BytesFromPhoto(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesFromPhoto", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BytesFromPhoto indicates an expected call of BytesFromPhoto.
func (mr *MockICalibrationAppMockRecorder) BytesFromPhoto(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesFromPhoto", reflect.TypeOf((*MockICalibrationApp)(nil).BytesFromPhoto), path)
}

// CalculateResult mocks base method.
func (m *MockICalibrationApp) CalculateResult(arg0 models.Calibration) (models.Calibration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateResult", arg0)
	ret0, _ := ret[0].(models.Calibration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateResult indicates an expected call of CalculateResult.
func (mr *MockICalibrationAppMockRecorder) CalculateResult(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateResult", reflect.TypeOf((*MockICalibrationApp)(nil).CalculateResult), arg0)
}

// CalibrationHandshake mocks base method.
func (m *MockICalibrationApp) CalibrationHandshake() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalibrationHandshake")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalibrationHandshake indicates an expected call of CalibrationHandshake.
func (mr *MockICalibrationAppMockRecorder) CalibrationHandshake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalibrationHandshake", reflect.TypeOf((*MockICalibrationApp)(nil).CalibrationHandshake))
}

// Clear mocks base method.
func (m *MockICalibrationApp) Clear(sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockICalibrationAppMockRecorder) Clear(sessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockICalibrationApp)(nil).Clear), sessionId)
}

// GetPhoto mocks base method.
func (m *MockICalibrationApp) GetPhoto(sessionId, number string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhoto", sessionId, number)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhoto indicates an expected call of GetPhoto.
func (mr *MockICalibrationAppMockRecorder) GetPhoto(sessionId, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhoto", reflect.TypeOf((*MockICalibrationApp)(nil).GetPhoto), sessionId, number)
}

// Save mocks base method.
func (m *MockICalibrationApp) Save(sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockICalibrationAppMockRecorder) Save(sessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockICalibrationApp)(nil).Save), sessionId)
}
