// Code generated by MockGen. DO NOT EDIT.
// Source: receipts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIReceiptsApp is a mock of IReceiptsApp interface.
type MockIReceiptsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIReceiptsAppMockRecorder
}

// MockIReceiptsAppMockRecorder is the mock recorder for MockIReceiptsApp.
type MockIReceiptsAppMockRecorder struct {
	mock *MockIReceiptsApp
}

// NewMockIReceiptsApp creates a new mock instance.
func NewMockIReceiptsApp(ctrl *gomock.Controller) *MockIReceiptsApp {
	mock := &MockIReceiptsApp{ctrl: ctrl}
	mock.recorder = &MockIReceiptsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReceiptsApp) EXPECT() *MockIReceiptsAppMockRecorder {
	return m.recorder
}

// AddReceipts mocks base method.
func (m *MockIReceiptsApp) AddReceipts(arg0 models.Receipts) (models.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReceipts", arg0)
	ret0, _ := ret[0].(models.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddReceipts indicates an expected call of AddReceipts.
func (mr *MockIReceiptsAppMockRecorder) AddReceipts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReceipts", reflect.TypeOf((*MockIReceiptsApp)(nil).AddReceipts), arg0)
}

// DeleteReceipts mocks base method.
func (m *MockIReceiptsApp) DeleteReceipts(arg0 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReceipts", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReceipts indicates an expected call of DeleteReceipts.
func (mr *MockIReceiptsAppMockRecorder) DeleteReceipts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReceipts", reflect.TypeOf((*MockIReceiptsApp)(nil).DeleteReceipts), arg0)
}

// GetReceipts mocks base method.
func (m *MockIReceiptsApp) GetReceipts() ([]models.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipts")
	ret0, _ := ret[0].([]models.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceipts indicates an expected call of GetReceipts.
func (mr *MockIReceiptsAppMockRecorder) GetReceipts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipts", reflect.TypeOf((*MockIReceiptsApp)(nil).GetReceipts))
}

// GetReceiptsByReceipt mocks base method.
func (m *MockIReceiptsApp) GetReceiptsByReceipt(arg0 int) (models.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiptsByReceipt", arg0)
	ret0, _ := ret[0].(models.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiptsByReceipt indicates an expected call of GetReceiptsByReceipt.
func (mr *MockIReceiptsAppMockRecorder) GetReceiptsByReceipt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiptsByReceipt", reflect.TypeOf((*MockIReceiptsApp)(nil).GetReceiptsByReceipt), arg0)
}

// UpdateReceipts mocks base method.
func (m *MockIReceiptsApp) UpdateReceipts(arg0 models.Receipts) (models.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReceipts", arg0)
	ret0, _ := ret[0].(models.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReceipts indicates an expected call of UpdateReceipts.
func (mr *MockIReceiptsAppMockRecorder) UpdateReceipts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReceipts", reflect.TypeOf((*MockIReceiptsApp)(nil).UpdateReceipts), arg0)
}
