// Code generated by MockGen. DO NOT EDIT.
// Source: placement.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIPlacementsApp is a mock of IPlacementsApp interface.
type MockIPlacementsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIPlacementsAppMockRecorder
}

// MockIPlacementsAppMockRecorder is the mock recorder for MockIPlacementsApp.
type MockIPlacementsAppMockRecorder struct {
	mock *MockIPlacementsApp
}

// NewMockIPlacementsApp creates a new mock instance.
func NewMockIPlacementsApp(ctrl *gomock.Controller) *MockIPlacementsApp {
	mock := &MockIPlacementsApp{ctrl: ctrl}
	mock.recorder = &MockIPlacementsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlacementsApp) EXPECT() *MockIPlacementsAppMockRecorder {
	return m.recorder
}

// AddPlacement mocks base method.
func (m *MockIPlacementsApp) AddPlacement(arg0 models.Placement) (models.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlacement", arg0)
	ret0, _ := ret[0].(models.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPlacement indicates an expected call of AddPlacement.
func (mr *MockIPlacementsAppMockRecorder) AddPlacement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlacement", reflect.TypeOf((*MockIPlacementsApp)(nil).AddPlacement), arg0)
}

// DeletePlacement mocks base method.
func (m *MockIPlacementsApp) DeletePlacement(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlacement", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePlacement indicates an expected call of DeletePlacement.
func (mr *MockIPlacementsAppMockRecorder) DeletePlacement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlacement", reflect.TypeOf((*MockIPlacementsApp)(nil).DeletePlacement), arg0)
}

// FillPlacement mocks base method.
func (m *MockIPlacementsApp) FillPlacement(arg0 models.FillPlacement) (models.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillPlacement", arg0)
	ret0, _ := ret[0].(models.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FillPlacement indicates an expected call of FillPlacement.
func (mr *MockIPlacementsAppMockRecorder) FillPlacement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillPlacement", reflect.TypeOf((*MockIPlacementsApp)(nil).FillPlacement), arg0)
}

// GetPlacementByBunker mocks base method.
func (m *MockIPlacementsApp) GetPlacementByBunker(arg0 string) (models.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacementByBunker", arg0)
	ret0, _ := ret[0].(models.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlacementByBunker indicates an expected call of GetPlacementByBunker.
func (mr *MockIPlacementsAppMockRecorder) GetPlacementByBunker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacementByBunker", reflect.TypeOf((*MockIPlacementsApp)(nil).GetPlacementByBunker), arg0)
}

// GetPlacements mocks base method.
func (m *MockIPlacementsApp) GetPlacements() ([]models.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacements")
	ret0, _ := ret[0].([]models.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlacements indicates an expected call of GetPlacements.
func (mr *MockIPlacementsAppMockRecorder) GetPlacements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacements", reflect.TypeOf((*MockIPlacementsApp)(nil).GetPlacements))
}

// UpdatePlacement mocks base method.
func (m *MockIPlacementsApp) UpdatePlacement(arg0 models.Placement) (models.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlacement", arg0)
	ret0, _ := ret[0].(models.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlacement indicates an expected call of UpdatePlacement.
func (mr *MockIPlacementsAppMockRecorder) UpdatePlacement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlacement", reflect.TypeOf((*MockIPlacementsApp)(nil).UpdatePlacement), arg0)
}
