// Code generated by MockGen. DO NOT EDIT.
// Source: users.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIUsersApp is a mock of IUsersApp interface.
type MockIUsersApp struct {
	ctrl     *gomock.Controller
	recorder *MockIUsersAppMockRecorder
}

// MockIUsersAppMockRecorder is the mock recorder for MockIUsersApp.
type MockIUsersAppMockRecorder struct {
	mock *MockIUsersApp
}

// NewMockIUsersApp creates a new mock instance.
func NewMockIUsersApp(ctrl *gomock.Controller) *MockIUsersApp {
	mock := &MockIUsersApp{ctrl: ctrl}
	mock.recorder = &MockIUsersAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsersApp) EXPECT() *MockIUsersAppMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockIUsersApp) ChangePassword(arg0 models.UpdatePassword) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockIUsersAppMockRecorder) ChangePassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockIUsersApp)(nil).ChangePassword), arg0)
}

// CheckAllUsers mocks base method.
func (m *MockIUsersApp) CheckAllUsers() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAllUsers")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAllUsers indicates an expected call of CheckAllUsers.
func (mr *MockIUsersAppMockRecorder) CheckAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAllUsers", reflect.TypeOf((*MockIUsersApp)(nil).CheckAllUsers))
}

// GetUserById mocks base method.
func (m *MockIUsersApp) GetUserById(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockIUsersAppMockRecorder) GetUserById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockIUsersApp)(nil).GetUserById), arg0)
}

// LoginUser mocks base method.
func (m *MockIUsersApp) LoginUser(user models.User) (*models.TokenResponse, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", user)
	ret0, _ := ret[0].(*models.TokenResponse)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIUsersAppMockRecorder) LoginUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIUsersApp)(nil).LoginUser), user)
}

// RegisterUser mocks base method.
func (m *MockIUsersApp) RegisterUser(user models.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockIUsersAppMockRecorder) RegisterUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockIUsersApp)(nil).RegisterUser), user)
}

// RemoveUser mocks base method.
func (m *MockIUsersApp) RemoveUser(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockIUsersAppMockRecorder) RemoveUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockIUsersApp)(nil).RemoveUser), arg0)
}

// Update mocks base method.
func (m *MockIUsersApp) Update(arg0 models.User) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIUsersAppMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUsersApp)(nil).Update), arg0)
}
