// Code generated by MockGen. DO NOT EDIT.
// Source: deviceSettings.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIDeviceSettingsApp is a mock of IDeviceSettingsApp interface.
type MockIDeviceSettingsApp struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceSettingsAppMockRecorder
}

// MockIDeviceSettingsAppMockRecorder is the mock recorder for MockIDeviceSettingsApp.
type MockIDeviceSettingsAppMockRecorder struct {
	mock *MockIDeviceSettingsApp
}

// NewMockIDeviceSettingsApp creates a new mock instance.
func NewMockIDeviceSettingsApp(ctrl *gomock.Controller) *MockIDeviceSettingsApp {
	mock := &MockIDeviceSettingsApp{ctrl: ctrl}
	mock.recorder = &MockIDeviceSettingsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeviceSettingsApp) EXPECT() *MockIDeviceSettingsAppMockRecorder {
	return m.recorder
}

// AddSetting mocks base method.
func (m *MockIDeviceSettingsApp) AddSetting(arg0 models.DeviceSettings) (models.DeviceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSetting", arg0)
	ret0, _ := ret[0].(models.DeviceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSetting indicates an expected call of AddSetting.
func (mr *MockIDeviceSettingsAppMockRecorder) AddSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSetting", reflect.TypeOf((*MockIDeviceSettingsApp)(nil).AddSetting), arg0)
}

// DeleteSetting mocks base method.
func (m *MockIDeviceSettingsApp) DeleteSetting(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSetting", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSetting indicates an expected call of DeleteSetting.
func (mr *MockIDeviceSettingsAppMockRecorder) DeleteSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSetting", reflect.TypeOf((*MockIDeviceSettingsApp)(nil).DeleteSetting), arg0)
}

// GetSettings mocks base method.
func (m *MockIDeviceSettingsApp) GetSettings() ([]models.DeviceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings")
	ret0, _ := ret[0].([]models.DeviceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockIDeviceSettingsAppMockRecorder) GetSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockIDeviceSettingsApp)(nil).GetSettings))
}

// GetSettingsByKey mocks base method.
func (m *MockIDeviceSettingsApp) GetSettingsByKey(arg0 string) (models.DeviceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsByKey", arg0)
	ret0, _ := ret[0].(models.DeviceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsByKey indicates an expected call of GetSettingsByKey.
func (mr *MockIDeviceSettingsAppMockRecorder) GetSettingsByKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsByKey", reflect.TypeOf((*MockIDeviceSettingsApp)(nil).GetSettingsByKey), arg0)
}

// UpdateSetting mocks base method.
func (m *MockIDeviceSettingsApp) UpdateSetting(arg0 models.DeviceSettings) (models.DeviceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetting", arg0)
	ret0, _ := ret[0].(models.DeviceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSetting indicates an expected call of UpdateSetting.
func (mr *MockIDeviceSettingsAppMockRecorder) UpdateSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetting", reflect.TypeOf((*MockIDeviceSettingsApp)(nil).UpdateSetting), arg0)
}
