// Code generated by MockGen. DO NOT EDIT.
// Source: seed.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockISeedsApp is a mock of ISeedsApp interface.
type MockISeedsApp struct {
	ctrl     *gomock.Controller
	recorder *MockISeedsAppMockRecorder
}

// MockISeedsAppMockRecorder is the mock recorder for MockISeedsApp.
type MockISeedsAppMockRecorder struct {
	mock *MockISeedsApp
}

// NewMockISeedsApp creates a new mock instance.
func NewMockISeedsApp(ctrl *gomock.Controller) *MockISeedsApp {
	mock := &MockISeedsApp{ctrl: ctrl}
	mock.recorder = &MockISeedsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISeedsApp) EXPECT() *MockISeedsAppMockRecorder {
	return m.recorder
}

// AddSeed mocks base method.
func (m *MockISeedsApp) AddSeed(arg0 models.Seeds) (models.Seeds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSeed", arg0)
	ret0, _ := ret[0].(models.Seeds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSeed indicates an expected call of AddSeed.
func (mr *MockISeedsAppMockRecorder) AddSeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSeed", reflect.TypeOf((*MockISeedsApp)(nil).AddSeed), arg0)
}

// DeleteSeed mocks base method.
func (m *MockISeedsApp) DeleteSeed(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeed", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSeed indicates an expected call of DeleteSeed.
func (mr *MockISeedsAppMockRecorder) DeleteSeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeed", reflect.TypeOf((*MockISeedsApp)(nil).DeleteSeed), arg0)
}

// GetSeedBySeed mocks base method.
func (m *MockISeedsApp) GetSeedBySeed(arg0 string) (models.Seeds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeedBySeed", arg0)
	ret0, _ := ret[0].(models.Seeds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeedBySeed indicates an expected call of GetSeedBySeed.
func (mr *MockISeedsAppMockRecorder) GetSeedBySeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeedBySeed", reflect.TypeOf((*MockISeedsApp)(nil).GetSeedBySeed), arg0)
}

// GetSeedWithBunkers mocks base method.
func (m *MockISeedsApp) GetSeedWithBunkers(arg0 string) ([]models.SeedsWithBunker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeedWithBunkers", arg0)
	ret0, _ := ret[0].([]models.SeedsWithBunker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeedWithBunkers indicates an expected call of GetSeedWithBunkers.
func (mr *MockISeedsAppMockRecorder) GetSeedWithBunkers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeedWithBunkers", reflect.TypeOf((*MockISeedsApp)(nil).GetSeedWithBunkers), arg0)
}

// GetSeeds mocks base method.
func (m *MockISeedsApp) GetSeeds() ([]models.Seeds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeeds")
	ret0, _ := ret[0].([]models.Seeds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeeds indicates an expected call of GetSeeds.
func (mr *MockISeedsAppMockRecorder) GetSeeds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeeds", reflect.TypeOf((*MockISeedsApp)(nil).GetSeeds))
}

// UpdateSeed mocks base method.
func (m *MockISeedsApp) UpdateSeed(arg0 models.Seeds) (models.Seeds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeed", arg0)
	ret0, _ := ret[0].(models.Seeds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSeed indicates an expected call of UpdateSeed.
func (mr *MockISeedsAppMockRecorder) UpdateSeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeed", reflect.TypeOf((*MockISeedsApp)(nil).UpdateSeed), arg0)
}
