// Code generated by MockGen. DO NOT EDIT.
// Source: recipes.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/qaZar1/GreenSeeds/microservices/greenSeeds/internal/models"
)

// MockIRecipesApp is a mock of IRecipesApp interface.
type MockIRecipesApp struct {
	ctrl     *gomock.Controller
	recorder *MockIRecipesAppMockRecorder
}

// MockIRecipesAppMockRecorder is the mock recorder for MockIRecipesApp.
type MockIRecipesAppMockRecorder struct {
	mock *MockIRecipesApp
}

// NewMockIRecipesApp creates a new mock instance.
func NewMockIRecipesApp(ctrl *gomock.Controller) *MockIRecipesApp {
	mock := &MockIRecipesApp{ctrl: ctrl}
	mock.recorder = &MockIRecipesAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecipesApp) EXPECT() *MockIRecipesAppMockRecorder {
	return m.recorder
}

// AddRecipes mocks base method.
func (m *MockIRecipesApp) AddRecipes(arg0 models.Recipes) (models.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecipes", arg0)
	ret0, _ := ret[0].(models.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecipes indicates an expected call of AddRecipes.
func (mr *MockIRecipesAppMockRecorder) AddRecipes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecipes", reflect.TypeOf((*MockIRecipesApp)(nil).AddRecipes), arg0)
}

// DeleteRecipes mocks base method.
func (m *MockIRecipesApp) DeleteRecipes(arg0 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipes", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecipes indicates an expected call of DeleteRecipes.
func (mr *MockIRecipesAppMockRecorder) DeleteRecipes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipes", reflect.TypeOf((*MockIRecipesApp)(nil).DeleteRecipes), arg0)
}

// GetRecipes mocks base method.
func (m *MockIRecipesApp) GetRecipes() ([]models.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipes")
	ret0, _ := ret[0].([]models.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipes indicates an expected call of GetRecipes.
func (mr *MockIRecipesAppMockRecorder) GetRecipes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipes", reflect.TypeOf((*MockIRecipesApp)(nil).GetRecipes))
}

// GetRecipesByRecipe mocks base method.
func (m *MockIRecipesApp) GetRecipesByRecipe(arg0 int) (models.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipesByRecipe", arg0)
	ret0, _ := ret[0].(models.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipesByRecipe indicates an expected call of GetRecipesByRecipe.
func (mr *MockIRecipesAppMockRecorder) GetRecipesByRecipe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipesByRecipe", reflect.TypeOf((*MockIRecipesApp)(nil).GetRecipesByRecipe), arg0)
}

// UpdateRecipes mocks base method.
func (m *MockIRecipesApp) UpdateRecipes(arg0 models.Recipes) (models.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipes", arg0)
	ret0, _ := ret[0].(models.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecipes indicates an expected call of UpdateRecipes.
func (mr *MockIRecipesAppMockRecorder) UpdateRecipes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipes", reflect.TypeOf((*MockIRecipesApp)(nil).UpdateRecipes), arg0)
}
